import type { Metadata } from 'next';
import Header from '@/components/ui/Layout/Header/Header';
import Footer from '@/components/ui/Layout/Footer/Footer';
import './styles/globals.scss';

export const metadata: Metadata = {
  title: 'BubbleHost | Луший хостинг Minecraft Java Edition',
  description: 'Generated by create next app',
  icons: { icon: '/favicon/site-logo.svg' },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Header />
        <main className="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
